# ------------------------------------------------------------------------------
# Pre-commit / PR — Secret Scan
# ------------------------------------------------------------------------------
# Runs on every push and PR to detect committed secrets (API keys, passwords,
# private keys). Why: Secrets in repo lead to credential theft and compliance
# failures. Catching them before merge prevents rotation burden and exposure.
# We use Gitleaks; alternatives: TruffleHog, GitGuardian. Fail the job if
# any secret is found so the commit cannot merge until removed and key rotated.
# ------------------------------------------------------------------------------
name: Secret Scan
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for scan)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Fail on any finding; do not allow secrets in repo
          GITLEAKS_ENABLE_COMMENTS: "true"
